#!/bin/bash
echo Running input parser

# Run the input parser to create two files for fastlas and the solver
python fastlas_input_parser.py ../experiments/fastlast.lp

echo Running Fastlas to find appropriate rules

## Run Fastlas on the fastlas input, provide the input and output files
#cd /Users/kritisapra/Desktop/Imperial/Fourth_Year/prob_aspal/fastlas_implementations/implementation
#cmake --build .
./FastLAS --file_name /Users/kritisapra/Desktop/Imperial/Fourth_Year/prob_aspal/fastlas_implementations/temp/fastlas_input.las --output_file /Users/kritisapra/Desktop/Imperial/Fourth_Year/prob_aspal/fastlas_implementations/temp/fastlas_input.las
#
## Run the solver on everything
#cd ..
#python prob_aspal_solver.py ./temp/prob_background_input.lp /Users/kritisapra/Desktop/Imperial/Fourth_Year/prob_aspal/fastlas_implementations/temp/fastlas_output_rules.txt
#
#echo Search Space Reduced